# Generated by Django 4.1.1 on 2022-11-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id_setor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('dias_de_trabalho', models.CharField(max_length=7)),
                ('horário_de_trabalho', models.CharField(max_length=12)),
            ],
        ),
    ]
