# Generated by Django 4.1.1 on 2022-11-24 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setor',
            old_name='nome',
            new_name='nome_setor',
        ),
    ]
