# Generated by Django 4.1.1 on 2022-11-24 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0002_rename_nome_setor_nome_setor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setor',
            old_name='dias_de_trabalho',
            new_name='dias_de_Trabalho',
        ),
        migrations.RenameField(
            model_name='setor',
            old_name='horário_de_trabalho',
            new_name='horário_de_Trabalho',
        ),
        migrations.RenameField(
            model_name='setor',
            old_name='id_setor',
            new_name='id_Setor',
        ),
        migrations.RenameField(
            model_name='setor',
            old_name='nome_setor',
            new_name='nome_Setor',
        ),
    ]
