# Generated by Django 4.1.1 on 2022-11-25 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nome',
            new_name='nome_cliente',
        ),
    ]
