# Generated by Django 4.1.1 on 2022-11-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id_veiculo', models.AutoField(primary_key=True, serialize=False)),
                ('fabricante', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=100)),
                ('data_de_Aquisicao', models.CharField(max_length=100)),
                ('ano', models.CharField(max_length=4)),
                ('chassi', models.CharField(max_length=100)),
            ],
        ),
    ]
