# Generated by Django 4.1.1 on 2022-11-24 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabricante', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fabricante',
            old_name='cor',
            new_name='data_de_Abertura',
        ),
        migrations.RenameField(
            model_name='fabricante',
            old_name='id_veiculo',
            new_name='id_Fabricante',
        ),
        migrations.RenameField(
            model_name='fabricante',
            old_name='fabricante',
            new_name='nome_Fabricante',
        ),
        migrations.RenameField(
            model_name='fabricante',
            old_name='modelo',
            new_name='pais_de_Origem',
        ),
    ]
