# Generated by Django 4.1.1 on 2022-11-25 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabricante', '0002_rename_cor_fabricante_data_de_abertura_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fabricante',
            old_name='chassi',
            new_name='atividade',
        ),
        migrations.RenameField(
            model_name='fabricante',
            old_name='data_de_Aquisicao',
            new_name='codigo_Postal',
        ),
        migrations.RenameField(
            model_name='fabricante',
            old_name='nome_Fabricante',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='fabricante',
            old_name='placa',
            new_name='nome_Fantasia',
        ),
        migrations.RemoveField(
            model_name='fabricante',
            name='ano',
        ),
    ]
