# Generated by Django 4.1.1 on 2022-11-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricante', '0003_rename_chassi_fabricante_atividade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricante',
            name='socios',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
