# Generated by Django 4.1.1 on 2022-11-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricante', '0004_fabricante_socios'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricante',
            name='CNPJ',
            field=models.CharField(default='', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fabricante',
            name='municipio',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fabricante',
            name='nome_Fabricante',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
