# Generated by Django 4.1.1 on 2022-11-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('simulacao', models.CharField(max_length=100)),
                ('condicao_Pagamento', models.CharField(max_length=100)),
                ('finaciamento', models.CharField(max_length=100)),
                ('status_Aprovacao', models.CharField(max_length=100)),
                ('documentacao_Necessaria', models.CharField(max_length=100)),
            ],
        ),
    ]
