# Generated by Django 4.1.1 on 2022-11-25 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_compra_nota_fiscal2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='nota_fiscal2',
        ),
    ]
