# Generated by Django 4.1.1 on 2022-11-25 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_compra_nota_fiscal2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='id_compra',
            new_name='id_Compra',
        ),
        migrations.RenameField(
            model_name='compra',
            old_name='nota_fiscal2',
            new_name='nota_fiscal',
        ),
    ]
