# Generated by Django 4.1.1 on 2022-11-24 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='data_Aquisicao',
            new_name='data_de_Aquisicao',
        ),
    ]
