# Generated by Django 4.1.1 on 2022-11-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_Funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_Funcionario', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=11)),
                ('CPF', models.CharField(max_length=11)),
            ],
        ),
    ]
